# Generated by Django 5.2.8 on 2025-11-07 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('pedido', '0002_itemcarrito_producto_itempedido_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='cliente',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carrito', to='client.cliente'),
        ),
    ]
